// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace RusLat2.ML
{
  public class ModelOutput
  {
    [ColumnName("PredictedLabel")]
    public String Prediction { get; set; }

    public float[] Score { get; set; }
  } // class ModelOutput

} // namespace RusLat2.ML
